[package]
name = "enrichdatagen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
csv = "1.1.6"
rand = "0.8.4"
serde = "1.0.130"
serde_json = "1.0.67"
